spring:
  application:
    name: Smart-Mall-Java
  datasource:
    url: jdbc:mysql://112.124.51.119:3306/smart_mall?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&defaultAuthenticationPlugin=mysql_native_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Root@12345678
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wechat:
  appid:  wxfd3e2415330ac983
  secret: abbba581442d9c95ea25a11907730bc3
jwt:
  secret: h2mPp9lbITbEk6H8q1N7LgqYIHDvX7PFwGsSWfKJH2c=

